name: Build and Deploy Docker Images

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v*']
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Deploy to Docker Hub
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: asymworks/jadetree-backend
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}-alpha
          type=semver,pattern={{major}}-alpha
          type=ref

    - uses: docker/setup-qemu-action@master
      with:
        platforms: all

    - uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Publish
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name == 'release' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6
